version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    env_file:
      - .env
    environment:
      FLASK_DEBUG: "off"
      FLASK_APP: ./backend/app.py
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static